paths:
  cohort_csv: SalaryAnalysis/data/cohort_local.csv
  local_cohort_csv: SalaryAnalysis/data/cohort_local.csv
  staff_csv:  SalaryAnalysis/data/staff.csv
  out_dir:    SalaryAnalysis/outputs

cohort:
  target_percentile: 50
  target_inflation: 0.00
nonlinear:
  base_salary: 55000
  exp_base_per_year: 1800
  exp_half_life_years: 20
  sen_base_per_year: 0
  sen_half_life_years: 0
  ma_pct: 0.04
  phd_pct: 0.08
  stack_degrees: false
  w_skill: 0
  w_prep: 0
  w_knowledge: 0
  level_adders: {LS: 0, MS: 0, HS: 0}
  aim_multiplier: 1.0
  f_non_sen: 0.67   # non-seniority years credit

piecewise:
  edges: [0,5,10,15,20,25,30,35,40,45]
  round_base: 100
  round_step: 50
  enforce_continuity: true
  shrink_to_total: 1  # or null
  prep_bonus: 2500

experience_policy:
  cap_outside_years: 50
  skill_endorsement_col: "Skill Endorsement"   # set to null/"" if you don’t have this column
  extra_years_per_skill: 5

consultant:
  target_percentile: 50
  inflation: 0.00
  deg_ma_pct: 0.04
  deg_phd_pct: 0.08
  pre_degree_down_pct: 0.04
  # bonuses
  prep_col: "Prep Rating"
  prep_bonus: 0
  skill_col: "Skill Rating"
  skill_bonus: 0
  lead_col: "Leadership Rating"
  leadership_bonus: 0

consultant_capped:
  enabled: true
  # inherit anything you omit from 'consultant'
  max_salary: 105000

planning:
  bump: 0.03
  tol: 0.00
  keep_above_uplift: 0.03
  faculty_size: 87.5

plots:
  plus_minus_pct: 0.08
  include_models: ["Real","NLM","RPB","PW"]

median_target:
  inflation: 0.00
  pre_degree_down_pct: 0.04
  deg_ma_pct: 0.04
  deg_phd_pct: 0.08
  prep_col: "Prep"
  prep_bonus: 0
  skill_col: "Skill Rating"
  skill_bonus: 0
  lead_col: "Leadership Rating"
  leadership_bonus: 0
  max_salary: 105000
  # labels must match your cohort bands in `long`
  band_targets:
    "0-5":   55000
    "6-10":  65000
    "11-15": 70000
    "16-20": 75000
    "21-25": 80000
    "26-30": 85000
    "31-35": 87000
    "36-40": 89000
    "41+":   90000